name: Run Pytest on Push and PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable chromium-chromedriver

      - name: Start Xvfb (Virtual Display)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Set Display
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Start FastAPI server (run in background)
        run: |
          uvicorn app.main:app --host 127.0.0.1 --port 8000 --log-level debug > logs.log 2>&1 &
          sleep 5  # ✅ 等待 5 秒，確保 FastAPI 啟動
          curl -I http://127.0.0.1:8000 || (echo "❌ FastAPI 沒有正確啟動！" && exit 1)

      - name: Debug FastAPI logs
        run: |
          ls -l logs.log || echo "❌ logs.log 不存在"
          cat logs.log || echo "❌ No log file found"
        
      - name: Run tests with Pytest
        run: pytest --maxfail=1 --disable-warnings --tb=short
